### ISSUE TITLE
Is this project accepting PRs?

### ISSUE THREAD

**Issue by Savuri** [Aleph-One-Ltd/yaffs2#2]
I want to make PR to fix llvm compiler warnings listed below. Will it be accepted?

yaffs_cache.c:44:6: error: no previous prototype for function 'yaffs_flush_single_cache' [-Werror,-Wmissing-prototypes]
void yaffs_flush_single_cache(struct yaffs_cache *cache, int discard)
     ^
yaffs_cache.c:44:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
void yaffs_flush_single_cache(struct yaffs_cache *cache, int discard)
^
static 

yaffs_checkptrw.c:181:14: error: variable 'state' is uninitialized when used here [-Werror,-Wuninitialized]
                                i, (int) state,
                                         ^~~~~
ydirectenv.h:86:32: note: expanded from macro 'yaffs_trace'
                printf("yaffs: " fmt "\n", ##__VA_ARGS__); \
                                             ^~~~~~~~~~~                              
yaffs_checkptrw.c:173:4: note: variable 'state' is declared here
                        enum yaffs_block_state state;
                        ^

yaffs_guts.c:702:6: error: explicitly assigning value of variable of type 'struct yaffs_dev *' to itself [-Werror,-Wself-assign]
        dev = dev;
        ~~~ ^ ~~~


yaffs_verify.c:232:6: error: variable 'required_depth' set but not used [-Werror,-Wunused-but-set-variable]
        int required_depth;
            ^


yaffs_yaffs1.c:31:6: error: variable 'deleted' set but not used [-Werror,-Wunused-but-set-variable]
        int deleted;
            ^


yaffs_yaffs2.c:557:21: error: no previous prototype for function 'yaffs2_do_endian_tnode_copy' [-Werror,-Wmissing-prototypes]
struct yaffs_tnode *yaffs2_do_endian_tnode_copy(struct yaffs_dev *dev,
                    ^
yaffs_yaffs2.c:557:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
struct yaffs_tnode *yaffs2_do_endian_tnode_copy(struct yaffs_dev *dev,
^
static

**Comment by cdhmanning** [comment]
I have never dealt with PRs on github before (only on different platforms).

If you are able to submit a PR then I will see about merging it.

Thanks

Charles
